### ISSUE TITLE
[question] What method/model do you use for the disparity map? 

### ISSUE THREAD

**Issue by roimulia2** [JuewenPeng/BokehMe#2]
Hey, loved the paper! 

I'm curious, what did you use to generate the disparity map? I'm thinking this could be also used to segment the most focused object in a given picture. Could be cool!

**Comment by JuewenPeng** [comment]
Thank you for loving. We use DPT (https://github.com/isl-org/DPT) to generate demo results due to its good generalization ability. Of course, you can also try other disparity prediction models since our model is not very sensitive to inaccurate disparity inputs.
