### ISSUE TITLE
Could you please provide a link of the EBB dataset?

### ISSUE THREAD

**Issue by CaptainEven** [JuewenPeng/BokehMe#6]
Because the original link disappear now 2023.08

**Comment by JuewenPeng** [comment]
You mean the original EBB! dataset released by the AIM competition or my post-processed dataset EBB400?

**Comment by CaptainEven** [comment]
> t-

the original EBB! 

> You mean the original EBB! dataset released by the AIM competition or my post-processed dataset EBB400?

I mean the original EBB, after registration, i can not find any download link
![image](https://github.com/JuewenPeng/BokehMe/assets/9303747/bb8c07f8-94ce-4d19-a335-d960e1a7176e)

**Comment by JuewenPeng** [comment]
![image](https://github.com/JuewenPeng/BokehMe/assets/38718148/898ed861-8958-47a6-b472-a27e5f4e142e)
![image](https://github.com/JuewenPeng/BokehMe/assets/38718148/e9de0130-ea82-41ad-9631-6e016caa0bd5)

https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/Training.zip
https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/ValidationBokehFree.zip
https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/TestBokehFree.zip

**Comment by CaptainEven** [comment]
Thanks for the awesome work and help!

**Comment by xuhangc** [comment]
H

> ![image](https://private-user-images.githubusercontent.com/38718148/263283970-898ed861-8958-47a6-b472-a27e5f4e142e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTgzODEsIm5iZiI6MTcxODk1ODA4MSwicGF0aCI6Ii8zODcxODE0OC8yNjMyODM5NzAtODk4ZWQ4NjEtODk1OC00N2E2LWI0NzItYTI3ZTVmNGUxNDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA4MjEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0OWM5NTY4N2RlOTE1YmYwZTAyOGMwMTRjNGEyOGFiMDY5MTNhZmY4NjBiMjQyMGJkM2Q4NjZkYmYxMzUzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9t_-bYhYnwNDQkupck1pQgQZZ_8lFgKe8ukdEC60hU8) ![image](https://private-user-images.githubusercontent.com/38718148/263283999-e9de0130-ea82-41ad-9631-6e016caa0bd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTgzODEsIm5iZiI6MTcxODk1ODA4MSwicGF0aCI6Ii8zODcxODE0OC8yNjMyODM5OTktZTlkZTAxMzAtZWE4Mi00MWFkLTk2MzEtNmUwMTZjYWEwYmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA4MjEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NGRlNzI4YjNkYTVkNmFhNTIwNDVlZGE3ZjAwYTZjM2UwMDgxMjY0NTJmMTJhMmE0NjMwZGE3M2E0MDhmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TsvbQkDqlQUh0WWs5B12zHqMooh8nrWTiqAaVm0DQVI)
> 
> https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/Training.zip https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/ValidationBokehFree.zip https://data.vision.ee.ethz.ch/timofter/AIM19Bokeh/TestBokehFree.zip

Hi, these links are expired. Do you have any backups for sharing?

**Comment by JuewenPeng** [comment]
链接：https://pan.baidu.com/s/1u_-wXqHj_beGeGSMsyXR6w?pwd=lrsq 
提取码：lrsq 
--来自百度网盘超级会员V8的分享

Note that the disparity directory in the training set is produced by the depth estimation method MiDaS, not belonging to the original dataset.

**Comment by xuhangc** [comment]
> 链接：https://pan.baidu.com/s/1u_-wXqHj_beGeGSMsyXR6w?pwd=lrsq 提取码：lrsq --来自百度网盘超级会员V8的分享
> 
> Note that the disparity directory in the training set is produced by the depth estimation method MiDaS, not belonging to the original dataset.

Great thanks!
