### ISSUE TITLE
blur degree

### ISSUE THREAD

**Issue by C-water** [JuewenPeng/BokehMe#9]
Hi, juewen! Thank you for the BLB and training datasets.

I tried to train a CNN network to generate bokeh images in an end-to-end manner. When K=10 or 20 (the training set and the BLB are equally blur), the output is normal. However, when K increases from 30 to 50, the model cannot learn the corresponding degree of blur from the input defocus map. How did you solve this problem when training neural render (in Bokehme)?

Thank you very much!!!

**Comment by JuewenPeng** [comment]
With the increase of K, it will be much harder for the neural renderer to learn, since it needs to deal with a wider range of blur amounts. You can try to increase the capacity of the network or modify the architecture. However, from my experience, constraining the blur range of ARNet to a low level (eg. 0-10 or 0-12), and iteratively increase the blur range by IUNet is more efficient and effective.

**Comment by C-water** [comment]
Thank you for your reply.

I tried to increase the model capacity and the blur effect seemed to increase, along with artifacts (difficult to learn the defocus blur of unknown degree). As you suggested, I will adopt the iteratively up-sampling structure, such as IUNet, to increase the blur range.

Thank you again!!!

**Comment by EleFreelance** [comment]
> Hi, juewen! Thank you for the BLB and training datasets.
> 
> I tried to train a CNN network to generate bokeh images in an end-to-end manner. When K=10 or 20 (the training set and the BLB are equally blur), the output is normal. However, when K increases from 30 to 50, the model cannot learn the corresponding degree of blur from the input defocus map. How did you solve this problem when training neural render (in Bokehme)?
> 
> Thank you very much!!!

Hi, Sir, could you please add me as a WeChat or QQ friend? I would like to consult about some issues I encountered while trying to reproduce bokeh me.

Thank you very much!!!  @C-water
